#!/bin/bash

# Navigate to the current directory
cd "$(dirname "$0")" || { echo "Failed to navigate to script directory. Exiting..."; exit 1; }

# Make the script executable
echo "[*] Making script executable..."
chmod +x scope || { echo "Failed to make script executable. Exiting..."; exit 1; }

# Create symbolic link for 'scope'
echo "[*] Creating symbolic link..."
ln -sf "$(pwd)/scope" /data/data/com.termux/files/usr/bin/scope || { echo "Failed to create symbolic link. Exiting..."; exit 1; }

echo "[✔] Setup complete! You can now execute the tool by typing 'scope'."
